/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#e2dfff',
        'secondary-container': '#b6b4ff',
        'on-primary-container': '#dad7ff',
        'on-tertiary-fixed-variant': '#7b2f00',
        'primary': '#3525cd',
        'on-background': '#191c1d',
        'surface-variant': '#e1e3e4',
        'on-surface': '#191c1d',
        'tertiary-container': '#a44100',
        'surface-container-low': '#f3f4f5',
        'outline-variant': '#c7c4d8',
        'outline': '#777587',
        'inverse-primary': '#c3c0ff',
        'on-secondary-fixed': '#140f54',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#ffb695',
        'surface-container-highest': '#e1e3e4',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#c3c0ff',
        'surface': '#f8f9fa',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#413f82',
        'surface-dim': '#d9dadb',
        'secondary': '#58579b',
        'primary-container': '#4f46e5',
        'on-surface-variant': '#464555',
        'on-tertiary-container': '#ffd2be',
        'on-primary-fixed': '#0f0069',
        'on-primary-fixed-variant': '#3323cc',
        'secondary-fixed': '#e2dfff',
        'secondary-fixed-dim': '#c3c0ff',
        'tertiary-fixed': '#ffdbcc',
        'on-secondary-container': '#454386',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f0f1f2',
        'background': '#f8f9fa',
        'on-primary': '#ffffff',
        'surface-bright': '#f8f9fa',
        'inverse-surface': '#2e3132',
        'surface-container': '#edeeef',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#351000',
        'surface-container-high': '#e7e8e9',
        'surface-tint': '#4d44e3',
        'tertiary': '#7e3000',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1.5rem',
        '2xl': '2rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
